import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Person, Recipe } from "schema-dts";
import { JsonLd, jsonLdScriptProps } from "react-schemaorg";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Schema App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          {...jsonLdScriptProps<Recipe>({
            "@context": "https://schema.org",
            "@type": "Recipe",
            name: "Non-alcoholic Pina Colada",
            image: [
              "https://example.com/photos/1x1/photo.jpg",
              "https://example.com/photos/4x3/photo.jpg",
              "https://example.com/photos/16x9/photo.jpg",
            ],
            author: {
              "@type": "Person",
              name: "Mary Stone",
            },
            datePublished: "2018-03-10",
            description:
              "This non-alcoholic pina colada is everyone's favorite!",
            recipeCuisine: "American",
            prepTime: "PT1M",
            cookTime: "PT2M",
            totalTime: "PT3M",
            keywords: "non-alcoholic",
            recipeYield: "1 serving",
            recipeCategory: "Drink",
            nutrition: {
              "@type": "NutritionInformation",
              calories: "120 calories",
            },
            aggregateRating: {
              "@type": "AggregateRating",
              ratingValue: "5",
              ratingCount: "18",
            },
            recipeIngredient: [
              "2 cups of pineapple juice",
              "5/8 cup cream of coconut",
              "ice",
            ],
            recipeInstructions: [
              {
                "@type": "HowToStep",
                text: "Blend 2 cups of pineapple juice and 5/8 cup cream of coconut until smooth.",
              },
              {
                "@type": "HowToStep",
                text: "Fill a glass with ice.",
              },
              {
                "@type": "HowToStep",
                text: "Pour the pineapple juice and coconut mixture over ice.",
              },
            ],
            video: {
              "@type": "VideoObject",
              name: "How to make a Party Coffee Cake",
              description: "This is how you make a Party Coffee Cake.",
              thumbnailUrl: [
                "https://example.com/photos/1x1/photo.jpg",
                "https://example.com/photos/4x3/photo.jpg",
                "https://example.com/photos/16x9/photo.jpg",
              ],
              contentUrl: "http://www.example.com/video123.mp4",
              embedUrl: "http://www.example.com/videoplayer?video=123",
              uploadDate: "2018-02-05T08:00:00+08:00",
              duration: "PT1M33S",
              interactionStatistic: {
                "@type": "InteractionCounter",
                interactionType: { "@type": "WatchAction" },
                userInteractionCount: 2347,
              },
              expires: "2019-02-05T08:00:00+08:00",
            },
          })}
        />
      </Head>

      <main className={styles.main}>
        <h3>Schema ORG Demo</h3>
        <div>
          Paste current url to{" "}
          <a
            style={{ color: "red" }}
            href="https://search.google.com/test/rich-results"
          >
            Google Schema Test Tool
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
